In [59]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import SGD
from torch.optim import Adam

class BaseNN(nn.Module):
    
    def __init__(self):
        super().__init__()

        self.w00 = nn.Parameter(torch.randn(1), requires_grad=False)
        self.b00 = nn.Parameter(torch.randn(1), requires_grad=False)
        self.w01 = nn.Parameter(torch.randn(1), requires_grad=False)

        self.w10 = nn.Parameter(torch.randn(1), requires_grad=False)
        self.b10 = nn.Parameter(torch.randn(1), requires_grad=False)
        self.w11 = nn.Parameter(torch.randn(1), requires_grad=False)

        self.final_bias = nn.Parameter(torch.randn(1), requires_grad=False)

    def forward(self, input):
        node_00_output = F.relu(self.w00 * input + self.b00)
        node_10_output = F.relu(self.w10 * input + self.b10)
        
        node_final_output = F.relu(self.w01 * node_00_output + self.w11 * node_10_output + self.final_bias)
        return node_final_output
 

In [4]:
inputs = torch.linspace(start=0, end=10, steps=100)
# print(inputs)

model = BaseNN()
results = model(inputs)

print(results)


tensor([2.2349, 2.2439, 2.2530, 2.2620, 2.2711, 2.2801, 2.2891, 2.2982, 2.3072,
        2.3163, 2.3253, 2.3344, 2.3434, 2.3524, 2.3615, 2.3705, 2.3796, 2.3886,
        2.3976, 2.4067, 2.4157, 2.4248, 2.4338, 2.4429, 2.4519, 2.4609, 2.4700,
        2.4790, 2.4881, 2.4971, 2.5061, 2.5152, 2.5242, 2.5333, 2.5423, 2.5514,
        2.5604, 2.5694, 2.5785, 2.5875, 2.5966, 2.6056, 2.6147, 2.6237, 2.6327,
        2.6418, 2.6508, 2.6599, 2.6689, 2.6779, 2.6870, 2.6960, 2.7051, 2.7141,
        2.7232, 2.7322, 2.7412, 2.7503, 2.7593, 2.7684, 2.7774, 2.7864, 2.7955,
        2.8045, 2.8136, 2.8226, 2.8317, 2.8407, 2.8497, 2.8588, 2.8678, 2.8769,
        2.8859, 2.8949, 2.9040, 2.9130, 2.9221, 2.9311, 2.9402, 2.9492, 2.9582,
        2.9673, 2.9763, 2.9854, 2.9944, 3.0035, 3.0125, 3.0215, 3.0306, 3.0396,
        3.0487, 3.0577, 3.0667, 3.0758, 3.0848, 3.0939, 3.1029, 3.1120, 3.1210,
        3.1300])


In [18]:
class BaseNN_train(nn.Module):
    
    def __init__(self):
        super().__init__()

        self.w00 = nn.Parameter(torch.randn(1), requires_grad=True)
        self.b00 = nn.Parameter(torch.randn(1), requires_grad=True)
        self.w01 = nn.Parameter(torch.randn(1), requires_grad=True)
        self.w10 = nn.Parameter(torch.randn(1), requires_grad=True)
        self.b10 = nn.Parameter(torch.randn(1), requires_grad=True)
        self.w11 = nn.Parameter(torch.randn(1), requires_grad=True)

        self.final_bias = nn.Parameter(torch.randn(1), requires_grad=True)

    def forward(self, input):
        node_00_output = F.relu(self.w00 * input + self.b00)
        node_10_output = F.relu(self.w10 * input + self.b10)
        
        node_final_output = F.relu(self.w01 * node_00_output + self.w11 * node_10_output + self.final_bias)
        return node_final_output
 

In [139]:
inputs = torch.tensor([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=torch.float32)
labels = torch.tensor([ 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=torch.float32)

model = BaseNN_train()
# optimiser = SGD(model.parameters(), lr=0.1)
optimiser = Adam(model.parameters(), lr=0.1)

epochs = 1000
for epoch in range(epochs):
    iterations = len(inputs)

    total_loss = 0
    for i in range(iterations):
        input = inputs[i]
        label = labels[i]

        output = model(input)
        output = torch.sigmoid(output)
        label = label.reshape([1])
        # print(f"{output} {output.shape} | {label} {label.shape}")
        loss = F.binary_cross_entropy_with_logits(output, label)
        # loss = (output - label) ** 2
        # print(f"loss = {loss} | {output} , {label}")
        total_loss += float(loss)
        loss.backward()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {total_loss}")
    optimiser.step()
    optimiser.zero_grad()

print(model.w00, model.b00, model.w01, model.w10, model.b10, model.w11, model.final_bias)

Epoch 0, Loss: 10.898311406373978
Epoch 100, Loss: 9.214846849441528
Epoch 200, Loss: 9.214846849441528
Epoch 300, Loss: 9.214846849441528
Epoch 400, Loss: 9.214846849441528
Epoch 500, Loss: 9.214846849441528
Epoch 600, Loss: 9.214846849441528
Epoch 700, Loss: 9.214846849441528
Epoch 800, Loss: 9.214846849441528
Epoch 900, Loss: 9.214846849441528
Parameter containing:
tensor([-0.1167], requires_grad=True) Parameter containing:
tensor([-2.0093], requires_grad=True) Parameter containing:
tensor([0.2660], requires_grad=True) Parameter containing:
tensor([1.0911], requires_grad=True) Parameter containing:
tensor([1.6481], requires_grad=True) Parameter containing:
tensor([-2.4213], requires_grad=True) Parameter containing:
tensor([-0.7005], requires_grad=True)


In [ ]:
inputs = torch.linspace(start=0, end=10, steps=100)
# print(inputs)

model = BaseNN()
results = model(inputs)

print(results)


tensor([2.2349, 2.2439, 2.2530, 2.2620, 2.2711, 2.2801, 2.2891, 2.2982, 2.3072,
        2.3163, 2.3253, 2.3344, 2.3434, 2.3524, 2.3615, 2.3705, 2.3796, 2.3886,
        2.3976, 2.4067, 2.4157, 2.4248, 2.4338, 2.4429, 2.4519, 2.4609, 2.4700,
        2.4790, 2.4881, 2.4971, 2.5061, 2.5152, 2.5242, 2.5333, 2.5423, 2.5514,
        2.5604, 2.5694, 2.5785, 2.5875, 2.5966, 2.6056, 2.6147, 2.6237, 2.6327,
        2.6418, 2.6508, 2.6599, 2.6689, 2.6779, 2.6870, 2.6960, 2.7051, 2.7141,
        2.7232, 2.7322, 2.7412, 2.7503, 2.7593, 2.7684, 2.7774, 2.7864, 2.7955,
        2.8045, 2.8136, 2.8226, 2.8317, 2.8407, 2.8497, 2.8588, 2.8678, 2.8769,
        2.8859, 2.8949, 2.9040, 2.9130, 2.9221, 2.9311, 2.9402, 2.9492, 2.9582,
        2.9673, 2.9763, 2.9854, 2.9944, 3.0035, 3.0125, 3.0215, 3.0306, 3.0396,
        3.0487, 3.0577, 3.0667, 3.0758, 3.0848, 3.0939, 3.1029, 3.1120, 3.1210,
        3.1300])
